version : '3.7'
services :
    php-httpd :
        image : php:8.1-apache
        build : .
        ports :
            - 80:80
        volumes :
            - "./files:/var/www/html"
            - "./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
        links:
            - 'mariadb:db'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - XDEBUG_MODE=develop,debug

    nodejs:
        image: node
        ports: 
            - 8080:8083
        tty: true

    mariadb :
        image : mariadb:10.6
        volumes :
            - "./database:/var/lib/mysql"
            - "./custom.cnf:/etc/mysql/conf.d/custom.cnf"
        ports:
            - 3306:3306
        environment:
          TZ: "Europa/Madrid"
          MYSQL_DATABASE: "oversegurity"
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_USER: "security"
          MYSQL_PASSWORD: "security"

    phpmyadmin :
        image: phpmyadmin/phpmyadmin
        links:
            - 'mariadb:db'
        ports:
            - 8081:80
            
